import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'

// Try to pick up local certs from ./certs/ (generated by mkcert)
const certDir = path.resolve(__dirname, 'certs')
const keyPath = path.join(certDir, 'localhost-key.pem')
const certPath = path.join(certDir, 'localhost.pem')

let httpsConfig = false
if (fs.existsSync(keyPath) && fs.existsSync(certPath)) {
  httpsConfig = {
    key: fs.readFileSync(keyPath),
    cert: fs.readFileSync(certPath),
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    // bind to localhost only (prevents accessing via LAN IP)
    host: 'localhost',
    // enable HTTPS when certs are available in ./certs/
    https: httpsConfig,
    proxy: {
      '/api': 'http://localhost:5000',
    },
  },
})
